#!/usr/bin/env python3
import os
import urllib.parse

print("Content-Type: text/html\r")
print("\r")

query_string = os.environ.get('QUERY_STRING', '')
params = urllib.parse.parse_qs(query_string)
name = params.get('name', ['World'])[0]

print(f"""<!DOCTYPE html>
<html>
<head>
    <title>Hello CGI</title>
    <style>
        body {{ 
            font-family: Arial, sans-serif; 
            display: flex; 
            justify-content: center; 
            align-items: center; 
            min-height: 100vh; 
            margin: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }}
        .card {{
            background: white;
            padding: 40px;
            border-radius: 20px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            text-align: center;
        }}
        h1 {{ color: #333; font-size: 2.5em; }}
        .name {{ color: #667eea; }}
        a {{ color: #764ba2; }}
    </style>
</head>
<body>
    <div class="card">
        <h1>👋 Hello, <span class="name">{name}</span>!</h1>
        <p>This response was generated by a Python CGI script.</p>
        <p>Query string: <code>{query_string}</code></p>
        <p><a href="/test_webserv/">← Back to tests</a></p>
    </div>
</body>
</html>""")
